config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:show,:edit,:update]
  get "/search", to: "searches#search"
  get "/keyword_search", to: "searches#keyword_search"
  get "/reservations/confirm", to: "reservations#confirm"
  get "/reservations/:id/edit_confirm", to: "reservations#edit_confirm"
  root to: "searches#top"
  resources :rooms
  resources :reservations, only: [:index, :new, :confirm, :create, :show, :edit, :destroy, :update] do
    collection do
      post :confirm
      # patch :confirm
    end
    member do
      # post :edit_confirm
      patch :edit_confirm
    end
  end
  post '/rooms/:id', to: 'reservations#confirm'
  devise_for :users, module: "users"
  get "users/show" => "users#show"
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
  end

  def show
    @user = current_user
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
 <%= render "shared/partial" %>

 <%= render "shared/setting" %>

<h1>プロフィール編集</h1>

<%= form_with model: @user, url: user_registration_path, local: true do |f| %>
<table>
    <tr>
      <th><%= f.label :image ,"アイコン画像" %></th>
      <td><%= f.file_field :image %></td>
    </tr>

    <tr>
      <th><%= f.label :name ,"名前" %></th>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr>
      <th><%= f.label :profile ,"自己紹介" %></th>
      <td><%= f.text_field :profile %></td>
    </tr>
</table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する"%></li>
      <li><%= link_to "キャンセル", :back %></li>
    </ul>
  </div>


 <% if flash[:notice_no_update] %>
   <p class="notice"><%= flash[:notice_no_update] %></p>
 <% end %>

 <%= render "shared/error", obj: @user %> 
<% end %>

app/views/profiles/show.html.erb
 <%= render "shared/partial" %>

 <%= render "shared/setting" %>
<h2>プロフィール</h2>
<%= link_to "編集", edit_profile_path %>
<h3>アイコン画像</h3>
<%= @user.name %>
<h3>ユーザー名</h3>
<%= @user.name %>
<h3>自己紹介</h3>
<%= @user.profile %>