config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:show,:edit,:update]
  get "/search", to: "searches#search"
  get "/keyword_search", to: "searches#keyword_search"
  get "/reservations/confirm", to: "reservations#confirm"
  get "/reservations/:id/edit_confirm", to: "reservations#edit_confirm"
  root to: "searches#top"
  resources :rooms
  resources :reservations, only: [:index, :new, :confirm, :create, :show, :edit, :destroy, :update] do
    collection do
      post :confirm
      # patch :confirm
    end
    member do
      # post :edit_confirm
      patch :edit_confirm
    end
  end
  post '/rooms/:id', to: 'reservations#confirm'
  devise_for :users, module: "users"
  get "users/show" => "users#show"
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_partial.html.erb
<div class="partial">
    <header>
        <h4><%= link_to "宿泊予約アプリ", root_path %></h4>
      <% if user_signed_in? %>
    <div class="dropdown">
    <div class="dropdown__btn" id="dropdown__btn">
    <div>
      <% if @user.image.present? %>
      <img src=<%= @user.image %> class = "icon_image">
      <% else %>
      <img src=/default-user_image.png class = "icon_image">
      <% end %>
      <%= current_user.name %>
    </div>
  </div>
  <div class="dropdown__body">
    <ul class="dropdown__list">
      <li class="dropdown__item"><%= link_to "施設の新規登録", new_room_path %></li>
      <li class="dropdown__item"><%= link_to "予約済み一覧", reservations_path %></li>
      <li class="dropdown__item"><%= link_to "登録済み一覧", rooms_path %></li>
      <li class="dropdown__item"><%= link_to "アカウント設定", users_show_path %></li>
      <li class="dropdown__item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div>
      <% else %>
          <%= link_to "新規登録", new_user_registration_path %>
          <%= link_to "ログイン", new_user_session_path %>
      <% end %>
    </header>
</div>

<script>
    (function () {
  document.addEventListener('DOMContentLoaded', function() { 
    const btn = document.getElementById('dropdown__btn');
    if(btn) { 
      btn.addEventListener('click', function(){ 
        this.classList.toggle('is-open');
      });
    }
  });
}());
</script>

app/views/shared/_reservation.html.erb
<%# <%= form_with model: @reservation, url:confirm_reservations_path , local: true do |f| %>
<%= form_with(url:confirm_reservations_path, method: :get) do |f| %>
  <table>
    <tr>
      <th><%= f.label :checkin ,"チェックイン日" %></th>
      <td><%= f.date_field :checkin %></td>
    </tr>

    <tr>
      <th><%= f.label :checkout ,"チェックアウト日" %></th>
      <td><%= f.date_field :checkout %></td>
    </tr>

    <tr>
      <th><%= f.label :person ,"人数" %></th>
      <td><%= f.text_field :person %></td>
    </tr>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :room_id, value: @room.id %>
  </table>

 <% if flash[:notice_no_create] %>
   <p class="notice"><%= flash[:notice_no_create] %></p>
 <% end %>

  <div>
    <ul>
      <li><%= f.submit "予約", name: nil %></li>
      <li><%= link_to "キャンセル", :reservations %></li>
    </ul>
  </div>

<% end %>

app/views/shared/_setting.html.erb
<div class="setting">
<h1>設定</h1>
<%= link_to "プロフィール", profile_path(current_user.id) %>
<%= link_to "アカウント", users_show_path %>
</div>