config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:show,:edit,:update]
  get "/search", to: "searches#search"
  get "/keyword_search", to: "searches#keyword_search"
  get "/reservations/confirm", to: "reservations#confirm"
  get "/reservations/:id/edit_confirm", to: "reservations#edit_confirm"
  root to: "searches#top"
  resources :rooms
  resources :reservations, only: [:index, :new, :confirm, :create, :show, :edit, :destroy, :update] do
    collection do
      post :confirm
      # patch :confirm
    end
    member do
      # post :edit_confirm
      patch :edit_confirm
    end
  end
  post '/rooms/:id', to: 'reservations#confirm'
  devise_for :users, module: "users"
  get "users/show" => "users#show"
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_name, presence: true
    validates :room_content, presence: true
    validates :room_price_day, numericality: { greater_than_or_equal_to: 1 }
    validates :room_address, presence: true
    belongs_to :user
    has_many :reservations
    mount_uploader :room_image, RoomImageUploader

    def self.search(search)
      return Room.all unless search
      Room.where(['room_address LIKE ?', "%#{search}%"])
    end

    def self.keyword_search(keyword_search)
      return Room.all unless keyword_search
      Room.where(['room_name LIKE ? OR room_content LIKE ? ', "%#{keyword_search}%", "%#{keyword_search}%"])
    end
  end
  

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.where(user_id:current_user.id)
    @user = current_user
  end

  def new
    @room = Room.new
    @user = current_user
  end

  def create
    @room = Room.new(room_params)
    @user = current_user
    if @room.save
      flash[:notice_create] = "施設情報を登録しました"
      redirect_to :rooms
    else
      flash[:notice_no_create] = "施設情報の登録に失敗しました"
      redirect_to '/rooms/new'
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = current_user
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
    @user = current_user
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice_update] = "施設情報を更新しました"
      redirect_to :rooms
    else
      flash[:notice_no_update] = "施設情報を更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice_destroy] = "施設情報を削除しました"
    redirect_to :rooms
  end

   private
   def room_params  # プライベートメソッド 
     params.require(:room).permit(:room_name, :room_content, :room_price_day, :room_address, :room_image, :user_id, :room_id)
   end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
 <%= render "shared/partial" %>

<h3>施設情報の編集</h3>

<%= form_with model: @room do |f| %>
<table>
    <tr>
      <th><%= f.label :room_name ,"施設名" %></th>
      <td><%= f.text_field :room_name %></td>
    </tr>

    <tr>
      <th><%= f.label :room_content ,"施設詳細" %></th>
      <td><%= f.text_field :room_content %></td>
    </tr>

    <tr>
      <th><%= f.label :room_price_day ,"料金" %></th>
      <td><%= f.text_field :room_price_day %></td>
    </tr>

    <tr>
      <th><%= f.label :room_address ,"住所" %></th>
      <td><%= f.text_field :room_address %></td>
    </tr>

    <tr>
      <th><%= f.label :room_image ,"施設画像"  %></th>
      <td><%= f.file_field :room_image %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する"%></li>
      <li><%= link_to "キャンセル", :rooms %></li>
    </ul>
  </div>

 <% if flash[:notice_no_update] %>
   <p class="notice"><%= flash[:notice_no_update] %></p>
 <% end %>

 <%= render "shared/error", obj: @room %> 
<% end %>

app/views/rooms/index.html.erb
 <%= render "shared/partial" %>
<div style="display: flex;justify-content: space-between">
<h3>登録済み一覧</h3>
<p><%= link_to "施設の新規登録", :new_room %></p>
</div>

<div>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.room_image.present? %>
            <img src=<%= room.room_image %> class = "room_image">
          <% else %>
            <img src="/default-room_image.png" class = "room_image">
          <% end %>
        </td>
        <td><%= link_to "#{room.room_name}", room %></td>
        <td><%= room.room_content %></td>
        <td><%= room.room_price_day %></td>
        <td><%= l room.updated_at %></td>
        <td><%= link_to "編集", [:edit, room] %></td>
        <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 <% if flash[:notice_create] %>
   <p class="notice"><%= flash[:notice_create] %></p>
 <% end %>

 <% if flash[:notice_update] %>
   <p class="notice"><%= flash[:notice_update] %></p>
 <% end %>

 <% if flash[:notice_destroy] %>
   <p class="notice"><%= flash[:notice_destroy] %></p>
 <% end %>

</div>

app/views/rooms/new.html.erb
 <%= render "shared/partial" %>
<h3>施設の新規追加</h3>

<%= form_with model: @room do |f| %>
  <table>
    <tr>
      <th><%= f.label :room_name ,"施設名" %></th>
      <td><%= f.text_field :room_name, placeholder: 'ルーム名を入力' %></td>
    </tr>

    <tr>
      <th><%= f.label :room_content ,"施設詳細" %></th>
      <td><%= f.text_field :room_content, placeholder: '施設詳細を入力' %></td>
    </tr>

    <tr>
      <th><%= f.label :room_price_day ,"料金" %></th>
      <td><%= f.text_field :room_price_day, placeholder: '一日あたりの料金を入力' %></td>
    </tr>

    <tr>
      <th><%= f.label :room_address ,"住所" %></th>
      <td><%= f.text_field :room_address, placeholder: '住所を入力' %></td>
    </tr>
     <%= f.hidden_field :user_id, value: @user.id %>
  </table>

 <% if flash[:notice_no_create] %>
   <p class="notice"><%= flash[:notice_no_create] %></p>
 <% end %>

  <div>
    <ul>
      <li><%= f.submit "保存"%></li>
      <li><%= link_to "キャンセル", :rooms %></li>
    </ul>
  </div>

  <%= render "shared/error", obj: @room %> 
<% end %>

app/views/rooms/show.html.erb
 <%= render "shared/partial" %>

<%= link_to '戻る', :back %>

<%= link_to "編集", edit_room_path(@room.id) %>
<%= form_with model: @room do |f| %>
          <% if @room.room_image.present? %>
            <img src=<%= @room.room_image %> class = "room_image">
          <% else %>
            <img src="/default-room_image.png" class = "room_image">
          <% end %>
<table>
    <tr>
      <th><%= f.label :room_name ,"施設名" %></th>
      <td><%= @room.room_name %></td>
    </tr>

    <tr>
      <th><%= f.label :room_content ,"施設詳細" %></th>
      <td><%= @room.room_content %></td>
    </tr>

    <tr>
      <th><%= f.label :room_price_day ,"料金" %></th>
      <td><%= @room.room_price_day %></td>
    </tr>

    <tr>
      <th><%= f.label :room_address ,"住所" %></th>
      <td><%= @room.room_address %></td>
    </tr>
  </table>

<% end %>

 <%= render "shared/reservation" %>